### ISSUE TITLE
How to pass maxResult with TS?

### ISSUE THREAD

**Issue by pawan-poudel-github** [DrKain/scrape-youtube#69] opened 2023-09-21 09:44 UTC
How can I pass the number of videos length count in youtube.search()?

**Comment by DrKain** [comment] 2023-09-21 10:05
If you have any further questions you're welcome to contact me on Discord, I'll gladly help you with any problems or questions. I'll close this issue for now, seeing as it's a question not a bug report.    
Discord ID: drkain

**Closed by DrKain** 2023-09-21 10:05 UTC
Labels: question
